/********************************************************************
* MTreeIO.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error MTreeIO.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableMTreeIO();
extern void G__cpp_setup_inheritanceMTreeIO();
extern void G__cpp_setup_typetableMTreeIO();
extern void G__cpp_setup_memvarMTreeIO();
extern void G__cpp_setup_globalMTreeIO();
extern void G__cpp_setup_memfuncMTreeIO();
extern void G__cpp_setup_funcMTreeIO();
extern void G__set_cpp_environmentMTreeIO();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MTree/Lepton.h"
#include "MTree/Electron.h"
#include "MTree/Photon.h"
#include "MTree/EventInfo.h"
#include "MTree/Jet.h"
#include "MTree/MissingET.h"
#include "MTree/Muon.h"
#include "MTree/Track.h"
#include "MTree/PrimaryVertex.h"
#include "MTree/Trigger.h"
#include "MTree/TruthParticle.h"
#include "MTree/L1TriggerROI.h"
#include "MTree/HLTTriggerROI.h"
#include "MTree/TriggerObject.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__MTreeIOLN_TClass;
extern G__linked_taginfo G__MTreeIOLN_TBuffer;
extern G__linked_taginfo G__MTreeIOLN_TMemberInspector;
extern G__linked_taginfo G__MTreeIOLN_TObject;
extern G__linked_taginfo G__MTreeIOLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__MTreeIOLN_string;
extern G__linked_taginfo G__MTreeIOLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__MTreeIOLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MTreeIOLN_TClonesArray;
extern G__linked_taginfo G__MTreeIOLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__MTreeIOLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__MTreeIOLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__MTreeIOLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__MTreeIOLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__MTreeIOLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__MTreeIOLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__MTreeIOLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__MTreeIOLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__MTreeIOLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__MTreeIOLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__MTreeIOLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__MTreeIOLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__MTreeIOLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__MTreeIOLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__MTreeIOLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__MTreeIOLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__MTreeIOLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__MTreeIOLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__MTreeIOLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__MTreeIOLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__MTreeIOLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__MTreeIOLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__MTreeIOLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__MTreeIOLN_TLorentzVector;
extern G__linked_taginfo G__MTreeIOLN_TRef;
extern G__linked_taginfo G__MTreeIOLN_MTree;
extern G__linked_taginfo G__MTreeIOLN_MTreecLcLPrimaryVertex;
extern G__linked_taginfo G__MTreeIOLN_MTreecLcLTrack;
extern G__linked_taginfo G__MTreeIOLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__MTreeIOLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MTreeIOLN_MTreecLcLLepton;
extern G__linked_taginfo G__MTreeIOLN_MTreecLcLElectron;
extern G__linked_taginfo G__MTreeIOLN_MTreecLcLPhoton;
extern G__linked_taginfo G__MTreeIOLN_MTreecLcLEventInfo;
extern G__linked_taginfo G__MTreeIOLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__MTreeIOLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__MTreeIOLN_TMatrixTSymlEdoublegR;
extern G__linked_taginfo G__MTreeIOLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__MTreeIOLN_TMatrixTSparselEdoublegR;
extern G__linked_taginfo G__MTreeIOLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__MTreeIOLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__MTreeIOLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__MTreeIOLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__MTreeIOLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__MTreeIOLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__MTreeIOLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__MTreeIOLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__MTreeIOLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__MTreeIOLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__MTreeIOLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__MTreeIOLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__MTreeIOLN_maplEstringcOfloatcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOfloatgRsPgRsPgR;
extern G__linked_taginfo G__MTreeIOLN_MTreecLcLJet;
extern G__linked_taginfo G__MTreeIOLN_TObjString;
extern G__linked_taginfo G__MTreeIOLN_MTreecLcLMissingET;
extern G__linked_taginfo G__MTreeIOLN_MTreecLcLMuon;
extern G__linked_taginfo G__MTreeIOLN_MTreecLcLTrigger;
extern G__linked_taginfo G__MTreeIOLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__MTreeIOLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MTreeIOLN_TRefArray;
extern G__linked_taginfo G__MTreeIOLN_MTreecLcLTruthParticle;
extern G__linked_taginfo G__MTreeIOLN_MTreecLcLL1TriggerROI;
extern G__linked_taginfo G__MTreeIOLN_MTreecLcLHLTTriggerROI;
extern G__linked_taginfo G__MTreeIOLN_setlEintcOlesslEintgRcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__MTreeIOLN_setlEstringcOlesslEstringgRcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__MTreeIOLN_MTreecLcLTriggerObject;

/* STUB derived class for protected member access */
