//
// File generated by /net/share/root_5.20.00/bin/rootcint at Tue Jul 12 20:29:48 2011

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "fileUFj7AR.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

/********************************************************
* /net/s3_data_home/swalch/macro-cosmos/./macros/fileUFj7AR.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && (__GNUC__ > 3) && (__GNUC_MINOR__ > 1)
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablefileUFj7AR();

extern "C" void G__set_cpp_environmentfileUFj7AR() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("/net/s3_data_home/swalch/macro-cosmos/./macros/hww.cxx");
  G__cpp_reset_tagtablefileUFj7AR();
}
#include <new>
extern "C" int G__cpp_dllrevfileUFj7AR() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* Setting up global function */
static int G__fileUFj7AR__0_2744(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         string* pobj;
         string xobj = makeString((int) G__int(libp->para[0]));
         pobj = new string(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__fileUFj7AR__0_2745(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      hww(*((string*) G__int(libp->para[0])), (bool) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      hww(*((string*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   case 0:
      hww();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}


/*********************************************************
* Member function Stub
*********************************************************/

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncfileUFj7AR {
 public:
  G__Sizep2memfuncfileUFj7AR(): p(&G__Sizep2memfuncfileUFj7AR::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncfileUFj7AR::*p)();
};

size_t G__get_sizep2memfuncfileUFj7AR()
{
  G__Sizep2memfuncfileUFj7AR a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancefileUFj7AR() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablefileUFj7AR() {

   /* Setting up typedef entry */
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__fileUFj7ARLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__fileUFj7ARLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::string>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__fileUFj7ARLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__fileUFj7ARLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Double_t>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_TMatrixTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Double_t>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_TMatrixTRow_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Double_t>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_TMatrixTColumn_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Double_t>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_TMatrixTDiag_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Double_t>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_TMatrixTFlat_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Double_t>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_TMatrixTSub_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Double_t>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_TMatrixTSparseRow_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Double_t>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_TMatrixTSparseDiag_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Double_t>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_TMatrixTRowlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Double_t>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_TMatrixTColumnlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Double_t>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_TMatrixTDiaglEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Double_t>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_TMatrixTFlatlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Double_t>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_TMatrixTSublEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Double_t>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_TMatrixTSparseRowlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Double_t>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_TMatrixTSparseDiaglEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Double_t>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_TElementActionTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Double_t>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_TElementPosActionTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSym<Double_t>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_TMatrixTSymlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparse<Double_t>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_TMatrixTSparselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,float>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_maplEstringcOfloatcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOfloatgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<std::string>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_setlEstringcOlesslEstringgRcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Root::TLumiBlockRange>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_vectorlERootcLcLTLumiBlockRangecOallocatorlERootcLcLTLumiBlockRangegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_reverse_iteratorlEvectorlERootcLcLTLumiBlockRangecOallocatorlERootcLcLTLumiBlockRangegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__fileUFj7ARLN_vectorlERootcLcLTLumiBlockRangecOallocatorlERootcLcLTLumiBlockRangegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_reverse_iteratorlEvectorlERootcLcLTLumiBlockRangecOallocatorlERootcLcLTLumiBlockRangegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__fileUFj7ARLN_vectorlERootcLcLTLumiBlockRangecOallocatorlERootcLcLTLumiBlockRangegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<Int_t,TGoodRun>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_maplEintcORootcLcLTGoodRuncOlesslEintgRcOallocatorlEpairlEconstsPintcORootcLcLTGoodRungRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,Root::TGoodRun>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_maplEintcORootcLcLTGoodRuncOlesslEintgRcOallocatorlEpairlEconstsPintcORootcLcLTGoodRungRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,Root::TGoodRun,less<int>>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_maplEintcORootcLcLTGoodRuncOlesslEintgRcOallocatorlEpairlEconstsPintcORootcLcLTGoodRungRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<TString,TString>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_maplETStringcOTStringcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOTStringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<TString,TString,less<TString>>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_maplETStringcOTStringcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOTStringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Root::TGoodRun>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_vectorlERootcLcLTGoodRuncOallocatorlERootcLcLTGoodRungRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_reverse_iteratorlEvectorlERootcLcLTGoodRuncOallocatorlERootcLcLTGoodRungRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__fileUFj7ARLN_vectorlERootcLcLTGoodRuncOallocatorlERootcLcLTGoodRungRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_reverse_iteratorlEvectorlERootcLcLTGoodRuncOallocatorlERootcLcLTGoodRungRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__fileUFj7ARLN_vectorlERootcLcLTGoodRuncOallocatorlERootcLcLTGoodRungRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<TMsgLevel,std::string>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_maplERootcLcLTMsgLevelcOstringcOlesslERootcLcLTMsgLevelgRcOallocatorlEpairlEconstsPRootcLcLTMsgLevelcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<Root::TMsgLevel,string>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_maplERootcLcLTMsgLevelcOstringcOlesslERootcLcLTMsgLevelgRcOallocatorlEpairlEconstsPRootcLcLTMsgLevelcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<Root::TMsgLevel,string,less<Root::TMsgLevel>>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_maplERootcLcLTMsgLevelcOstringcOlesslERootcLcLTMsgLevelgRcOallocatorlEpairlEconstsPRootcLcLTMsgLevelcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TGoodRunsList>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_vectorlERootcLcLTGoodRunsListcOallocatorlERootcLcLTGoodRunsListgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_reverse_iteratorlEvectorlERootcLcLTGoodRunsListcOallocatorlERootcLcLTGoodRunsListgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__fileUFj7ARLN_vectorlERootcLcLTGoodRunsListcOallocatorlERootcLcLTGoodRunsListgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_reverse_iteratorlEvectorlERootcLcLTGoodRunsListcOallocatorlERootcLcLTGoodRunsListgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__fileUFj7ARLN_vectorlERootcLcLTGoodRunsListcOallocatorlERootcLcLTGoodRunsListgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Root::TGoodRunsList>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_vectorlERootcLcLTGoodRunsListcOallocatorlERootcLcLTGoodRunsListgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,TH2D*>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_maplEintcOTH2DmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTH2DmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,TH2D*,less<int>>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_maplEintcOTH2DmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTH2DmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,std::vector<std::string> >",117,G__get_linked_tagnum(&G__fileUFj7ARLN_maplEstringcOvectorlEstringcOallocatorlEstringgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,vector<string,allocator<string> >>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_maplEstringcOvectorlEstringcOallocatorlEstringgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,vector<string,allocator<string> >,less<string>>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_maplEstringcOvectorlEstringcOallocatorlEstringgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,double>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,std::string>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,string>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,string,less<string>>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<calibMap>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_vectorlEEnergyRescalercLcLcalibMapcOallocatorlEEnergyRescalercLcLcalibMapgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_reverse_iteratorlEvectorlEEnergyRescalercLcLcalibMapcOallocatorlEEnergyRescalercLcLcalibMapgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__fileUFj7ARLN_vectorlEEnergyRescalercLcLcalibMapcOallocatorlEEnergyRescalercLcLcalibMapgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_reverse_iteratorlEvectorlEEnergyRescalercLcLcalibMapcOallocatorlEEnergyRescalercLcLcalibMapgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__fileUFj7ARLN_vectorlEEnergyRescalercLcLcalibMapcOallocatorlEEnergyRescalercLcLcalibMapgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<EnergyRescaler::calibMap>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_vectorlEEnergyRescalercLcLcalibMapcOallocatorlEEnergyRescalercLcLcalibMapgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<MTree::TriggerObject*>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_vectorlEMTreecLcLTriggerObjectmUcOallocatorlEMTreecLcLTriggerObjectmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_reverse_iteratorlEvectorlEMTreecLcLTriggerObjectmUcOallocatorlEMTreecLcLTriggerObjectmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__fileUFj7ARLN_vectorlEMTreecLcLTriggerObjectmUcOallocatorlEMTreecLcLTriggerObjectmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_reverse_iteratorlEvectorlEMTreecLcLTriggerObjectmUcOallocatorlEMTreecLcLTriggerObjectmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__fileUFj7ARLN_vectorlEMTreecLcLTriggerObjectmUcOallocatorlEMTreecLcLTriggerObjectmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<MTree::Electron*>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_vectorlEMTreecLcLElectronmUcOallocatorlEMTreecLcLElectronmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_reverse_iteratorlEvectorlEMTreecLcLElectronmUcOallocatorlEMTreecLcLElectronmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__fileUFj7ARLN_vectorlEMTreecLcLElectronmUcOallocatorlEMTreecLcLElectronmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_reverse_iteratorlEvectorlEMTreecLcLElectronmUcOallocatorlEMTreecLcLElectronmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__fileUFj7ARLN_vectorlEMTreecLcLElectronmUcOallocatorlEMTreecLcLElectronmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<MTree::Muon*>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_vectorlEMTreecLcLMuonmUcOallocatorlEMTreecLcLMuonmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_reverse_iteratorlEvectorlEMTreecLcLMuonmUcOallocatorlEMTreecLcLMuonmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__fileUFj7ARLN_vectorlEMTreecLcLMuonmUcOallocatorlEMTreecLcLMuonmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_reverse_iteratorlEvectorlEMTreecLcLMuonmUcOallocatorlEMTreecLcLMuonmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__fileUFj7ARLN_vectorlEMTreecLcLMuonmUcOallocatorlEMTreecLcLMuonmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<MTree::Jet*>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_vectorlEMTreecLcLJetmUcOallocatorlEMTreecLcLJetmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_reverse_iteratorlEvectorlEMTreecLcLJetmUcOallocatorlEMTreecLcLJetmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__fileUFj7ARLN_vectorlEMTreecLcLJetmUcOallocatorlEMTreecLcLJetmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_reverse_iteratorlEvectorlEMTreecLcLJetmUcOallocatorlEMTreecLcLJetmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__fileUFj7ARLN_vectorlEMTreecLcLJetmUcOallocatorlEMTreecLcLJetmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TH1D*>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_maplEstringcOTH1DmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH1DmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TH1D*>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_maplEstringcOTH1DmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH1DmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TH1D*,less<string>>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_maplEstringcOTH1DmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH1DmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,std::vector<std::string> >",117,G__get_linked_tagnum(&G__fileUFj7ARLN_maplEintcOvectorlEstringcOallocatorlEstringgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,vector<string,allocator<string> >>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_maplEintcOvectorlEstringcOallocatorlEstringgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,vector<string,allocator<string> >,less<int>>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_maplEintcOvectorlEstringcOallocatorlEstringgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<MTree::Lepton*>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_vectorlEMTreecLcLLeptonmUcOallocatorlEMTreecLcLLeptonmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_reverse_iteratorlEvectorlEMTreecLcLLeptonmUcOallocatorlEMTreecLcLLeptonmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__fileUFj7ARLN_vectorlEMTreecLcLLeptonmUcOallocatorlEMTreecLcLLeptonmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_reverse_iteratorlEvectorlEMTreecLcLLeptonmUcOallocatorlEMTreecLcLLeptonmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__fileUFj7ARLN_vectorlEMTreecLcLLeptonmUcOallocatorlEMTreecLcLLeptonmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TH1D*>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__fileUFj7ARLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__fileUFj7ARLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,std::vector<TH1D*> >",117,G__get_linked_tagnum(&G__fileUFj7ARLN_maplEintcOvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlETH1DmUcOallocatorlETH1DmUgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,vector<TH1D*,allocator<TH1D*> >>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_maplEintcOvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlETH1DmUcOallocatorlETH1DmUgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,vector<TH1D*,allocator<TH1D*> >,less<int>>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_maplEintcOvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlETH1DmUcOallocatorlETH1DmUgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TH2D*>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_maplEstringcOTH2DmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH2DmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TH2D*>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_maplEstringcOTH2DmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH2DmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TH2D*,less<string>>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_maplEstringcOTH2DmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH2DmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,std::vector<int> >",117,G__get_linked_tagnum(&G__fileUFj7ARLN_maplEstringcOvectorlEintcOallocatorlEintgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,vector<int,allocator<int> >>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_maplEstringcOvectorlEintcOallocatorlEintgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,vector<int,allocator<int> >,less<string>>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_maplEstringcOvectorlEintcOallocatorlEintgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObject*>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_maplEstringcOTObjectmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjectmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObject*>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_maplEstringcOTObjectmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjectmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObject*,less<string>>",117,G__get_linked_tagnum(&G__fileUFj7ARLN_maplEstringcOTObjectmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjectmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */
extern "C" void G__cpp_setup_memvarfileUFj7AR() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/

/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncfileUFj7AR() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalfileUFj7AR() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
   G__memfunc_setup("makeString", 1045, G__fileUFj7AR__0_2744, 117, G__get_linked_tagnum(&G__fileUFj7ARLN_string), -1, 0, 1, 1, 1, 0, "i - - 0 - number", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("hww", 342, G__fileUFj7AR__0_2745, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'string' - 0 '\"testhww150\"' sample g - - 0 'false' debug", (char*) NULL
, (void*) NULL, 0);

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcfileUFj7AR() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__fileUFj7ARLN_TVectorTlEfloatgR = { "TVectorT<float>" , 97 , -1 };
G__linked_taginfo G__fileUFj7ARLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 97 , -1 };
G__linked_taginfo G__fileUFj7ARLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 97 , -1 };
G__linked_taginfo G__fileUFj7ARLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 97 , -1 };
G__linked_taginfo G__fileUFj7ARLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 97 , -1 };
G__linked_taginfo G__fileUFj7ARLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 97 , -1 };
G__linked_taginfo G__fileUFj7ARLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 97 , -1 };
G__linked_taginfo G__fileUFj7ARLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 97 , -1 };
G__linked_taginfo G__fileUFj7ARLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 97 , -1 };
G__linked_taginfo G__fileUFj7ARLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 97 , -1 };
G__linked_taginfo G__fileUFj7ARLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 97 , -1 };
G__linked_taginfo G__fileUFj7ARLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 97 , -1 };
G__linked_taginfo G__fileUFj7ARLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 97 , -1 };
G__linked_taginfo G__fileUFj7ARLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 97 , -1 };
G__linked_taginfo G__fileUFj7ARLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 97 , -1 };
G__linked_taginfo G__fileUFj7ARLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 97 , -1 };
G__linked_taginfo G__fileUFj7ARLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 97 , -1 };
G__linked_taginfo G__fileUFj7ARLN_TVectorTlEdoublegR = { "TVectorT<double>" , 97 , -1 };
G__linked_taginfo G__fileUFj7ARLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 97 , -1 };
G__linked_taginfo G__fileUFj7ARLN_TMatrixTlEdoublegR = { "TMatrixT<double>" , 97 , -1 };
G__linked_taginfo G__fileUFj7ARLN_TMatrixTSymlEdoublegR = { "TMatrixTSym<double>" , 97 , -1 };
G__linked_taginfo G__fileUFj7ARLN_TMatrixTSparselEdoublegR = { "TMatrixTSparse<double>" , 97 , -1 };
G__linked_taginfo G__fileUFj7ARLN_TMatrixTRow_constlEdoublegR = { "TMatrixTRow_const<double>" , 97 , -1 };
G__linked_taginfo G__fileUFj7ARLN_TMatrixTColumn_constlEdoublegR = { "TMatrixTColumn_const<double>" , 97 , -1 };
G__linked_taginfo G__fileUFj7ARLN_TMatrixTDiag_constlEdoublegR = { "TMatrixTDiag_const<double>" , 97 , -1 };
G__linked_taginfo G__fileUFj7ARLN_TMatrixTFlat_constlEdoublegR = { "TMatrixTFlat_const<double>" , 97 , -1 };
G__linked_taginfo G__fileUFj7ARLN_TMatrixTSub_constlEdoublegR = { "TMatrixTSub_const<double>" , 97 , -1 };
G__linked_taginfo G__fileUFj7ARLN_TMatrixTRowlEdoublegR = { "TMatrixTRow<double>" , 97 , -1 };
G__linked_taginfo G__fileUFj7ARLN_TMatrixTColumnlEdoublegR = { "TMatrixTColumn<double>" , 97 , -1 };
G__linked_taginfo G__fileUFj7ARLN_TMatrixTDiaglEdoublegR = { "TMatrixTDiag<double>" , 97 , -1 };
G__linked_taginfo G__fileUFj7ARLN_TMatrixTFlatlEdoublegR = { "TMatrixTFlat<double>" , 97 , -1 };
G__linked_taginfo G__fileUFj7ARLN_TMatrixTSublEdoublegR = { "TMatrixTSub<double>" , 97 , -1 };
G__linked_taginfo G__fileUFj7ARLN_TMatrixTSparseRow_constlEdoublegR = { "TMatrixTSparseRow_const<double>" , 97 , -1 };
G__linked_taginfo G__fileUFj7ARLN_TMatrixTSparseRowlEdoublegR = { "TMatrixTSparseRow<double>" , 97 , -1 };
G__linked_taginfo G__fileUFj7ARLN_TMatrixTSparseDiag_constlEdoublegR = { "TMatrixTSparseDiag_const<double>" , 97 , -1 };
G__linked_taginfo G__fileUFj7ARLN_TMatrixTSparseDiaglEdoublegR = { "TMatrixTSparseDiag<double>" , 97 , -1 };
G__linked_taginfo G__fileUFj7ARLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__fileUFj7ARLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__fileUFj7ARLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__fileUFj7ARLN_maplEstringcOfloatcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOfloatgRsPgRsPgR = { "map<string,float,less<string>,allocator<pair<const string,float> > >" , 99 , -1 };
G__linked_taginfo G__fileUFj7ARLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR = { "map<string,double,less<string>,allocator<pair<const string,double> > >" , 99 , -1 };
G__linked_taginfo G__fileUFj7ARLN_setlEstringcOlesslEstringgRcOallocatorlEstringgRsPgR = { "set<string,less<string>,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__fileUFj7ARLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__fileUFj7ARLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__fileUFj7ARLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__fileUFj7ARLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__fileUFj7ARLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__fileUFj7ARLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 };
G__linked_taginfo G__fileUFj7ARLN_TElementActionTlEdoublegR = { "TElementActionT<double>" , 99 , -1 };
G__linked_taginfo G__fileUFj7ARLN_TElementPosActionTlEdoublegR = { "TElementPosActionT<double>" , 99 , -1 };
G__linked_taginfo G__fileUFj7ARLN_vectorlERootcLcLTLumiBlockRangecOallocatorlERootcLcLTLumiBlockRangegRsPgR = { "vector<Root::TLumiBlockRange,allocator<Root::TLumiBlockRange> >" , 99 , -1 };
G__linked_taginfo G__fileUFj7ARLN_reverse_iteratorlEvectorlERootcLcLTLumiBlockRangecOallocatorlERootcLcLTLumiBlockRangegRsPgRcLcLiteratorgR = { "reverse_iterator<vector<Root::TLumiBlockRange,allocator<Root::TLumiBlockRange> >::iterator>" , 99 , -1 };
G__linked_taginfo G__fileUFj7ARLN_maplEintcORootcLcLTGoodRuncOlesslEintgRcOallocatorlEpairlEconstsPintcORootcLcLTGoodRungRsPgRsPgR = { "map<int,Root::TGoodRun,less<int>,allocator<pair<const int,Root::TGoodRun> > >" , 99 , -1 };
G__linked_taginfo G__fileUFj7ARLN_maplETStringcOTStringcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOTStringgRsPgRsPgR = { "map<TString,TString,less<TString>,allocator<pair<const TString,TString> > >" , 99 , -1 };
G__linked_taginfo G__fileUFj7ARLN_vectorlERootcLcLTGoodRuncOallocatorlERootcLcLTGoodRungRsPgR = { "vector<Root::TGoodRun,allocator<Root::TGoodRun> >" , 99 , -1 };
G__linked_taginfo G__fileUFj7ARLN_reverse_iteratorlEvectorlERootcLcLTGoodRuncOallocatorlERootcLcLTGoodRungRsPgRcLcLiteratorgR = { "reverse_iterator<vector<Root::TGoodRun,allocator<Root::TGoodRun> >::iterator>" , 99 , -1 };
G__linked_taginfo G__fileUFj7ARLN_maplERootcLcLTMsgLevelcOstringcOlesslERootcLcLTMsgLevelgRcOallocatorlEpairlEconstsPRootcLcLTMsgLevelcOstringgRsPgRsPgR = { "map<Root::TMsgLevel,string,less<Root::TMsgLevel>,allocator<pair<const Root::TMsgLevel,string> > >" , 99 , -1 };
G__linked_taginfo G__fileUFj7ARLN_vectorlERootcLcLTGoodRunsListcOallocatorlERootcLcLTGoodRunsListgRsPgR = { "vector<Root::TGoodRunsList,allocator<Root::TGoodRunsList> >" , 99 , -1 };
G__linked_taginfo G__fileUFj7ARLN_reverse_iteratorlEvectorlERootcLcLTGoodRunsListcOallocatorlERootcLcLTGoodRunsListgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<Root::TGoodRunsList,allocator<Root::TGoodRunsList> >::iterator>" , 99 , -1 };
G__linked_taginfo G__fileUFj7ARLN_maplEintcOTH2DmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTH2DmUgRsPgRsPgR = { "map<int,TH2D*,less<int>,allocator<pair<const int,TH2D*> > >" , 99 , -1 };
G__linked_taginfo G__fileUFj7ARLN_maplEstringcOvectorlEstringcOallocatorlEstringgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRsPgR = { "map<string,vector<string,allocator<string> >,less<string>,allocator<pair<const string,vector<string,allocator<string> > > > >" , 99 , -1 };
G__linked_taginfo G__fileUFj7ARLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR = { "map<string,string,less<string>,allocator<pair<const string,string> > >" , 99 , -1 };
G__linked_taginfo G__fileUFj7ARLN_vectorlEEnergyRescalercLcLcalibMapcOallocatorlEEnergyRescalercLcLcalibMapgRsPgR = { "vector<EnergyRescaler::calibMap,allocator<EnergyRescaler::calibMap> >" , 99 , -1 };
G__linked_taginfo G__fileUFj7ARLN_reverse_iteratorlEvectorlEEnergyRescalercLcLcalibMapcOallocatorlEEnergyRescalercLcLcalibMapgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<EnergyRescaler::calibMap,allocator<EnergyRescaler::calibMap> >::iterator>" , 99 , -1 };
G__linked_taginfo G__fileUFj7ARLN_vectorlEMTreecLcLTriggerObjectmUcOallocatorlEMTreecLcLTriggerObjectmUgRsPgR = { "vector<MTree::TriggerObject*,allocator<MTree::TriggerObject*> >" , 99 , -1 };
G__linked_taginfo G__fileUFj7ARLN_reverse_iteratorlEvectorlEMTreecLcLTriggerObjectmUcOallocatorlEMTreecLcLTriggerObjectmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<MTree::TriggerObject*,allocator<MTree::TriggerObject*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__fileUFj7ARLN_vectorlEMTreecLcLElectronmUcOallocatorlEMTreecLcLElectronmUgRsPgR = { "vector<MTree::Electron*,allocator<MTree::Electron*> >" , 99 , -1 };
G__linked_taginfo G__fileUFj7ARLN_reverse_iteratorlEvectorlEMTreecLcLElectronmUcOallocatorlEMTreecLcLElectronmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<MTree::Electron*,allocator<MTree::Electron*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__fileUFj7ARLN_vectorlEMTreecLcLMuonmUcOallocatorlEMTreecLcLMuonmUgRsPgR = { "vector<MTree::Muon*,allocator<MTree::Muon*> >" , 99 , -1 };
G__linked_taginfo G__fileUFj7ARLN_reverse_iteratorlEvectorlEMTreecLcLMuonmUcOallocatorlEMTreecLcLMuonmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<MTree::Muon*,allocator<MTree::Muon*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__fileUFj7ARLN_vectorlEMTreecLcLJetmUcOallocatorlEMTreecLcLJetmUgRsPgR = { "vector<MTree::Jet*,allocator<MTree::Jet*> >" , 99 , -1 };
G__linked_taginfo G__fileUFj7ARLN_reverse_iteratorlEvectorlEMTreecLcLJetmUcOallocatorlEMTreecLcLJetmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<MTree::Jet*,allocator<MTree::Jet*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__fileUFj7ARLN_maplEstringcOTH1DmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH1DmUgRsPgRsPgR = { "map<string,TH1D*,less<string>,allocator<pair<const string,TH1D*> > >" , 99 , -1 };
G__linked_taginfo G__fileUFj7ARLN_maplEintcOvectorlEstringcOallocatorlEstringgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRsPgR = { "map<int,vector<string,allocator<string> >,less<int>,allocator<pair<const int,vector<string,allocator<string> > > > >" , 99 , -1 };
G__linked_taginfo G__fileUFj7ARLN_vectorlEMTreecLcLLeptonmUcOallocatorlEMTreecLcLLeptonmUgRsPgR = { "vector<MTree::Lepton*,allocator<MTree::Lepton*> >" , 99 , -1 };
G__linked_taginfo G__fileUFj7ARLN_reverse_iteratorlEvectorlEMTreecLcLLeptonmUcOallocatorlEMTreecLcLLeptonmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<MTree::Lepton*,allocator<MTree::Lepton*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__fileUFj7ARLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR = { "vector<TH1D*,allocator<TH1D*> >" , 99 , -1 };
G__linked_taginfo G__fileUFj7ARLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TH1D*,allocator<TH1D*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__fileUFj7ARLN_maplEintcOvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlETH1DmUcOallocatorlETH1DmUgRsPgRsPgRsPgRsPgR = { "map<int,vector<TH1D*,allocator<TH1D*> >,less<int>,allocator<pair<const int,vector<TH1D*,allocator<TH1D*> > > > >" , 99 , -1 };
G__linked_taginfo G__fileUFj7ARLN_maplEstringcOTH2DmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH2DmUgRsPgRsPgR = { "map<string,TH2D*,less<string>,allocator<pair<const string,TH2D*> > >" , 99 , -1 };
G__linked_taginfo G__fileUFj7ARLN_maplEstringcOvectorlEintcOallocatorlEintgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR = { "map<string,vector<int,allocator<int> >,less<string>,allocator<pair<const string,vector<int,allocator<int> > > > >" , 99 , -1 };
G__linked_taginfo G__fileUFj7ARLN_maplEstringcOTObjectmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjectmUgRsPgRsPgR = { "map<string,TObject*,less<string>,allocator<pair<const string,TObject*> > >" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablefileUFj7AR() {
  G__fileUFj7ARLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__fileUFj7ARLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__fileUFj7ARLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__fileUFj7ARLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__fileUFj7ARLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__fileUFj7ARLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__fileUFj7ARLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__fileUFj7ARLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__fileUFj7ARLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__fileUFj7ARLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__fileUFj7ARLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__fileUFj7ARLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__fileUFj7ARLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__fileUFj7ARLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__fileUFj7ARLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__fileUFj7ARLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__fileUFj7ARLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__fileUFj7ARLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__fileUFj7ARLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__fileUFj7ARLN_TMatrixTlEdoublegR.tagnum = -1 ;
  G__fileUFj7ARLN_TMatrixTSymlEdoublegR.tagnum = -1 ;
  G__fileUFj7ARLN_TMatrixTSparselEdoublegR.tagnum = -1 ;
  G__fileUFj7ARLN_TMatrixTRow_constlEdoublegR.tagnum = -1 ;
  G__fileUFj7ARLN_TMatrixTColumn_constlEdoublegR.tagnum = -1 ;
  G__fileUFj7ARLN_TMatrixTDiag_constlEdoublegR.tagnum = -1 ;
  G__fileUFj7ARLN_TMatrixTFlat_constlEdoublegR.tagnum = -1 ;
  G__fileUFj7ARLN_TMatrixTSub_constlEdoublegR.tagnum = -1 ;
  G__fileUFj7ARLN_TMatrixTRowlEdoublegR.tagnum = -1 ;
  G__fileUFj7ARLN_TMatrixTColumnlEdoublegR.tagnum = -1 ;
  G__fileUFj7ARLN_TMatrixTDiaglEdoublegR.tagnum = -1 ;
  G__fileUFj7ARLN_TMatrixTFlatlEdoublegR.tagnum = -1 ;
  G__fileUFj7ARLN_TMatrixTSublEdoublegR.tagnum = -1 ;
  G__fileUFj7ARLN_TMatrixTSparseRow_constlEdoublegR.tagnum = -1 ;
  G__fileUFj7ARLN_TMatrixTSparseRowlEdoublegR.tagnum = -1 ;
  G__fileUFj7ARLN_TMatrixTSparseDiag_constlEdoublegR.tagnum = -1 ;
  G__fileUFj7ARLN_TMatrixTSparseDiaglEdoublegR.tagnum = -1 ;
  G__fileUFj7ARLN_string.tagnum = -1 ;
  G__fileUFj7ARLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__fileUFj7ARLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__fileUFj7ARLN_maplEstringcOfloatcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOfloatgRsPgRsPgR.tagnum = -1 ;
  G__fileUFj7ARLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR.tagnum = -1 ;
  G__fileUFj7ARLN_setlEstringcOlesslEstringgRcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__fileUFj7ARLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__fileUFj7ARLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__fileUFj7ARLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__fileUFj7ARLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__fileUFj7ARLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__fileUFj7ARLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__fileUFj7ARLN_TElementActionTlEdoublegR.tagnum = -1 ;
  G__fileUFj7ARLN_TElementPosActionTlEdoublegR.tagnum = -1 ;
  G__fileUFj7ARLN_vectorlERootcLcLTLumiBlockRangecOallocatorlERootcLcLTLumiBlockRangegRsPgR.tagnum = -1 ;
  G__fileUFj7ARLN_reverse_iteratorlEvectorlERootcLcLTLumiBlockRangecOallocatorlERootcLcLTLumiBlockRangegRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__fileUFj7ARLN_maplEintcORootcLcLTGoodRuncOlesslEintgRcOallocatorlEpairlEconstsPintcORootcLcLTGoodRungRsPgRsPgR.tagnum = -1 ;
  G__fileUFj7ARLN_maplETStringcOTStringcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOTStringgRsPgRsPgR.tagnum = -1 ;
  G__fileUFj7ARLN_vectorlERootcLcLTGoodRuncOallocatorlERootcLcLTGoodRungRsPgR.tagnum = -1 ;
  G__fileUFj7ARLN_reverse_iteratorlEvectorlERootcLcLTGoodRuncOallocatorlERootcLcLTGoodRungRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__fileUFj7ARLN_maplERootcLcLTMsgLevelcOstringcOlesslERootcLcLTMsgLevelgRcOallocatorlEpairlEconstsPRootcLcLTMsgLevelcOstringgRsPgRsPgR.tagnum = -1 ;
  G__fileUFj7ARLN_vectorlERootcLcLTGoodRunsListcOallocatorlERootcLcLTGoodRunsListgRsPgR.tagnum = -1 ;
  G__fileUFj7ARLN_reverse_iteratorlEvectorlERootcLcLTGoodRunsListcOallocatorlERootcLcLTGoodRunsListgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__fileUFj7ARLN_maplEintcOTH2DmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTH2DmUgRsPgRsPgR.tagnum = -1 ;
  G__fileUFj7ARLN_maplEstringcOvectorlEstringcOallocatorlEstringgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__fileUFj7ARLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR.tagnum = -1 ;
  G__fileUFj7ARLN_vectorlEEnergyRescalercLcLcalibMapcOallocatorlEEnergyRescalercLcLcalibMapgRsPgR.tagnum = -1 ;
  G__fileUFj7ARLN_reverse_iteratorlEvectorlEEnergyRescalercLcLcalibMapcOallocatorlEEnergyRescalercLcLcalibMapgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__fileUFj7ARLN_vectorlEMTreecLcLTriggerObjectmUcOallocatorlEMTreecLcLTriggerObjectmUgRsPgR.tagnum = -1 ;
  G__fileUFj7ARLN_reverse_iteratorlEvectorlEMTreecLcLTriggerObjectmUcOallocatorlEMTreecLcLTriggerObjectmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__fileUFj7ARLN_vectorlEMTreecLcLElectronmUcOallocatorlEMTreecLcLElectronmUgRsPgR.tagnum = -1 ;
  G__fileUFj7ARLN_reverse_iteratorlEvectorlEMTreecLcLElectronmUcOallocatorlEMTreecLcLElectronmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__fileUFj7ARLN_vectorlEMTreecLcLMuonmUcOallocatorlEMTreecLcLMuonmUgRsPgR.tagnum = -1 ;
  G__fileUFj7ARLN_reverse_iteratorlEvectorlEMTreecLcLMuonmUcOallocatorlEMTreecLcLMuonmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__fileUFj7ARLN_vectorlEMTreecLcLJetmUcOallocatorlEMTreecLcLJetmUgRsPgR.tagnum = -1 ;
  G__fileUFj7ARLN_reverse_iteratorlEvectorlEMTreecLcLJetmUcOallocatorlEMTreecLcLJetmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__fileUFj7ARLN_maplEstringcOTH1DmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH1DmUgRsPgRsPgR.tagnum = -1 ;
  G__fileUFj7ARLN_maplEintcOvectorlEstringcOallocatorlEstringgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__fileUFj7ARLN_vectorlEMTreecLcLLeptonmUcOallocatorlEMTreecLcLLeptonmUgRsPgR.tagnum = -1 ;
  G__fileUFj7ARLN_reverse_iteratorlEvectorlEMTreecLcLLeptonmUcOallocatorlEMTreecLcLLeptonmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__fileUFj7ARLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR.tagnum = -1 ;
  G__fileUFj7ARLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__fileUFj7ARLN_maplEintcOvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlETH1DmUcOallocatorlETH1DmUgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__fileUFj7ARLN_maplEstringcOTH2DmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH2DmUgRsPgRsPgR.tagnum = -1 ;
  G__fileUFj7ARLN_maplEstringcOvectorlEintcOallocatorlEintgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__fileUFj7ARLN_maplEstringcOTObjectmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjectmUgRsPgRsPgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablefileUFj7AR() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_TMatrixTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_TMatrixTSymlEdoublegR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_TMatrixTSparselEdoublegR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_TMatrixTRow_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_TMatrixTColumn_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_TMatrixTDiag_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_TMatrixTFlat_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_TMatrixTSub_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_TMatrixTRowlEdoublegR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_TMatrixTColumnlEdoublegR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_TMatrixTDiaglEdoublegR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_TMatrixTFlatlEdoublegR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_TMatrixTSublEdoublegR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_TMatrixTSparseRow_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_TMatrixTSparseRowlEdoublegR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_TMatrixTSparseDiag_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_TMatrixTSparseDiaglEdoublegR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_string);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_maplEstringcOfloatcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOfloatgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_setlEstringcOlesslEstringgRcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_vectorlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_TElementActionTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_TElementPosActionTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_vectorlERootcLcLTLumiBlockRangecOallocatorlERootcLcLTLumiBlockRangegRsPgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_reverse_iteratorlEvectorlERootcLcLTLumiBlockRangecOallocatorlERootcLcLTLumiBlockRangegRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_maplEintcORootcLcLTGoodRuncOlesslEintgRcOallocatorlEpairlEconstsPintcORootcLcLTGoodRungRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_maplETStringcOTStringcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOTStringgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_vectorlERootcLcLTGoodRuncOallocatorlERootcLcLTGoodRungRsPgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_reverse_iteratorlEvectorlERootcLcLTGoodRuncOallocatorlERootcLcLTGoodRungRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_maplERootcLcLTMsgLevelcOstringcOlesslERootcLcLTMsgLevelgRcOallocatorlEpairlEconstsPRootcLcLTMsgLevelcOstringgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_vectorlERootcLcLTGoodRunsListcOallocatorlERootcLcLTGoodRunsListgRsPgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_reverse_iteratorlEvectorlERootcLcLTGoodRunsListcOallocatorlERootcLcLTGoodRunsListgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_maplEintcOTH2DmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTH2DmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_maplEstringcOvectorlEstringcOallocatorlEstringgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_vectorlEEnergyRescalercLcLcalibMapcOallocatorlEEnergyRescalercLcLcalibMapgRsPgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_reverse_iteratorlEvectorlEEnergyRescalercLcLcalibMapcOallocatorlEEnergyRescalercLcLcalibMapgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_vectorlEMTreecLcLTriggerObjectmUcOallocatorlEMTreecLcLTriggerObjectmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_reverse_iteratorlEvectorlEMTreecLcLTriggerObjectmUcOallocatorlEMTreecLcLTriggerObjectmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_vectorlEMTreecLcLElectronmUcOallocatorlEMTreecLcLElectronmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_reverse_iteratorlEvectorlEMTreecLcLElectronmUcOallocatorlEMTreecLcLElectronmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_vectorlEMTreecLcLMuonmUcOallocatorlEMTreecLcLMuonmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_reverse_iteratorlEvectorlEMTreecLcLMuonmUcOallocatorlEMTreecLcLMuonmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_vectorlEMTreecLcLJetmUcOallocatorlEMTreecLcLJetmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_reverse_iteratorlEvectorlEMTreecLcLJetmUcOallocatorlEMTreecLcLJetmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_maplEstringcOTH1DmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH1DmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_maplEintcOvectorlEstringcOallocatorlEstringgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_vectorlEMTreecLcLLeptonmUcOallocatorlEMTreecLcLLeptonmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_reverse_iteratorlEvectorlEMTreecLcLLeptonmUcOallocatorlEMTreecLcLLeptonmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_maplEintcOvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlETH1DmUcOallocatorlETH1DmUgRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_maplEstringcOTH2DmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH2DmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_maplEstringcOvectorlEintcOallocatorlEintgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__fileUFj7ARLN_maplEstringcOTObjectmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjectmUgRsPgRsPgR);
}
extern "C" void G__cpp_setupfileUFj7AR(void) {
  G__check_setup_version(30051515,"G__cpp_setupfileUFj7AR()");
  G__set_cpp_environmentfileUFj7AR();
  G__cpp_setup_tagtablefileUFj7AR();

  G__cpp_setup_inheritancefileUFj7AR();

  G__cpp_setup_typetablefileUFj7AR();

  G__cpp_setup_memvarfileUFj7AR();

  G__cpp_setup_memfuncfileUFj7AR();
  G__cpp_setup_globalfileUFj7AR();
  G__cpp_setup_funcfileUFj7AR();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncfileUFj7AR();
  return;
}
class G__cpp_setup_initfileUFj7AR {
  public:
    G__cpp_setup_initfileUFj7AR() { G__add_setup_func("fileUFj7AR",(G__incsetup)(&G__cpp_setupfileUFj7AR)); G__call_setup_funcs(); }
   ~G__cpp_setup_initfileUFj7AR() { G__remove_setup_func("fileUFj7AR"); }
};
G__cpp_setup_initfileUFj7AR G__cpp_setup_initializerfileUFj7AR;

